spring.application.name=hospital
spring.jpa.hibernate.ddl-auto=update

# Configuración de Conexión a Filess.io (JDBC Estándar)
spring.datasource.url=jdbc:mysql://h5-dp9.h.filess.io:61002/hospital_seriousfar?useSSL=false&serverTimezone=UTC
spring.datasource.username=hospital_seriousfar
spring.datasource.password=cockycamel

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect