spring.application.name=hospital
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql: true
spring.datasource.url = jdbc:mysql://hospital_seriousfar:cockycamel@h5-dp9.h.filess.io:61002/hospital_seriousfar
spring.datasource.username=hospital_seriousfar
spring.datasource.password=cockycamel
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver